Repository Scently-itsuda/Scently-BE, pull requests merged in 2025-08, with the labels that each got.

#55 Feat: 알림 도메인 변경 및 신고 기능 구현
  src/main/java/com/itsuda/perfume/controller/NotificationController.java
  src/main/java/com/itsuda/perfume/controller/ReportController.java
  src/main/java/com/itsuda/perfume/domain/CommentLikeNotification.java
  src/main/java/com/itsuda/perfume/domain/Notification.java
  src/main/java/com/itsuda/perfume/domain/OotdCommentNotification.java
  src/main/java/com/itsuda/perfume/domain/PerfumeNotification.java
  src/main/java/com/itsuda/perfume/domain/PostCommentNotification.java
  src/main/java/com/itsuda/perfume/domain/PostLikeNotification.java
  src/main/java/com/itsuda/perfume/domain/Report.java
  src/main/java/com/itsuda/perfume/domain/Review.java
  src/main/java/com/itsuda/perfume/domain/type/NotificationType.java
  src/main/java/com/itsuda/perfume/domain/type/ReportTargetType.java
  src/main/java/com/itsuda/perfume/domain/type/ReportType.java
  src/main/java/com/itsuda/perfume/dto/request/report/CommentReportDto.java
  src/main/java/com/itsuda/perfume/dto/request/report/OotdReportDto.java
  src/main/java/com/itsuda/perfume/dto/request/report/PostReportDto.java
  src/main/java/com/itsuda/perfume/dto/request/report/ReviewReportDto.java
  src/main/java/com/itsuda/perfume/dto/response/notification/UserNotificationDto.java
  src/main/java/com/itsuda/perfume/dto/response/notification/UserNotificationsDto.java
  src/main/java/com/itsuda/perfume/dto/response/report/ReportedCommentDto.java
  src/main/java/com/itsuda/perfume/dto/response/report/ReportedOotdDto.java
  src/main/java/com/itsuda/perfume/dto/response/report/ReportedPostDto.java
  src/main/java/com/itsuda/perfume/dto/response/report/ReportedReviewDto.java
  src/main/java/com/itsuda/perfume/exception/ErrorCode.java
  src/main/java/com/itsuda/perfume/repository/NotificationRepository.java
  src/main/java/com/itsuda/perfume/repository/OotdCommentNotificationRepository.java
  src/main/java/com/itsuda/perfume/repository/OotdLikeNotificationRepository.java
  src/main/java/com/itsuda/perfume/repository/OotdRepository.java
  src/main/java/com/itsuda/perfume/repository/PostCommentNotificationRepository.java
  src/main/java/com/itsuda/perfume/repository/PostLikeNotificationRepository.java
  src/main/java/com/itsuda/perfume/repository/ReportRepository.java
  src/main/java/com/itsuda/perfume/repository/ReviewRepository.java
  src/main/java/com/itsuda/perfume/service/NotificationService.java
  src/main/java/com/itsuda/perfume/service/OotdService.java
  src/main/java/com/itsuda/perfume/service/PostService.java
  src/main/java/com/itsuda/perfume/service/ReportService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-test.yml
  src/test/java/com/itsuda/perfume/controller/NotificationControllerTest.java
  src/test/java/com/itsuda/perfume/controller/ReportControllerTest.java
  src/test/java/com/itsuda/perfume/repository/OotdRepositoryTest.java
  src/test/java/com/itsuda/perfume/service/NotificationServiceTest.java
  src/test/java/com/itsuda/perfume/service/OotdServiceTest.java
  src/test/java/com/itsuda/perfume/service/PostServiceTest.java
  src/test/java/com/itsuda/perfume/service/ReportServiceTest.java
Labels: 🎉 Feat, 🔨Fix

#56 Feat: S3 파일 업로드 기능 구현
  build.gradle
  src/main/java/com/itsuda/perfume/config/S3Config.java
  src/main/java/com/itsuda/perfume/exception/ErrorCode.java
  src/main/java/com/itsuda/perfume/service/OotdService.java
  src/main/java/com/itsuda/perfume/util/S3Util.java
  src/main/resources/application.yml
  src/test/java/com/itsuda/perfume/service/OotdServiceTest.java
Labels: 🎉 Feat

#59 fix: Perfume 테이블 discription 컬럼 속성 변경
  src/main/java/com/itsuda/perfume/domain/Perfume.java
Labels: 🔨Fix
